USE [master]
GO

/****** Object:  Database [StoreData]    Script Date: 1/7/2015 4:33:01 PM ******/
CREATE DATABASE [StoreData]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'StoreData', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\StoreData.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'StoreData_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\StoreData_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [StoreData] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [StoreData].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [StoreData] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [StoreData] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [StoreData] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [StoreData] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [StoreData] SET ARITHABORT OFF 
GO

ALTER DATABASE [StoreData] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [StoreData] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [StoreData] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [StoreData] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [StoreData] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [StoreData] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [StoreData] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [StoreData] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [StoreData] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [StoreData] SET  DISABLE_BROKER 
GO

ALTER DATABASE [StoreData] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [StoreData] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [StoreData] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [StoreData] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [StoreData] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [StoreData] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [StoreData] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [StoreData] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [StoreData] SET  MULTI_USER 
GO

ALTER DATABASE [StoreData] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [StoreData] SET DB_CHAINING OFF 
GO

ALTER DATABASE [StoreData] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [StoreData] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [StoreData] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [StoreData] SET  READ_WRITE 
GO

